import { CheckInSession } from './firebase'

export const MOCK_SESSIONS: CheckInSession[] = [
  {
    id: '1',
    initialMood: 40,
    city: 'Buenos Aires',
    news: { title: 'Economic Recovery', description: 'Argentina shows positive indicators' },
    opinion: 'La economía está mejorando lentamente pero hay esperanza para el futuro',
    selectedAgent: 'compassionate',
    agentResponse: 'Entiendo tu optimismo cautela',
    agentQuestion: '¿Qué te da más confianza?',
    followUpResponse: 'Los empleos están aumentando',
    finalMood: 65,
    moodShift: 25,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
    status: 'completed',
    currentStep: 4
  },
  {
    id: '2',
    initialMood: 55,
    city: 'Mexico City',
    news: { title: 'Cultural Festival', description: 'Major art exhibition opens' },
    opinion: 'Me emociona ver que nuestra cultura es celebrada globalmente',
    selectedAgent: 'reflective',
    agentResponse: 'La cultura es el corazón de la identidad',
    agentQuestion: '¿Qué significado tiene para ti?',
    followUpResponse: 'Es conexión con mis raíces',
    finalMood: 78,
    moodShift: 23,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 72000000,
    updatedAt: Date.now() - 72000000,
    status: 'completed',
    currentStep: 4
  },
  {
    id: '3',
    initialMood: 35,
    city: 'Lima',
    news: { title: 'Infrastructure Project', description: 'New metro line opens' },
    opinion: 'Finalmente hay inversión en transporte pero sigue siendo insuficiente',
    selectedAgent: 'analytical',
    agentResponse: 'Hay progreso pero con limitaciones reales',
    agentQuestion: '¿Qué cambios has notado?',
    followUpResponse: 'Menos tráfico en mi ruta diaria',
    finalMood: 52,
    moodShift: 17,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 60000000,
    updatedAt: Date.now() - 60000000,
    status: 'completed',
    currentStep: 4
  },
  {
    id: '4',
    initialMood: 60,
    city: 'Bogotá',
    news: { title: 'Peace Agreement', description: 'New peace accord reached' },
    opinion: 'Espero que esto traiga estabilidad real a nuestro país',
    selectedAgent: 'compassionate',
    agentResponse: 'La esperanza es un primer paso importante',
    agentQuestion: '¿Cómo te gustaría que fuera?',
    followUpResponse: 'Con oportunidades para todos',
    finalMood: 70,
    moodShift: 10,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 48000000,
    updatedAt: Date.now() - 48000000,
    status: 'completed',
    currentStep: 4
  },
  {
    id: '5',
    initialMood: 45,
    city: 'Santiago',
    news: { title: 'Labor Rights', description: 'New labor protections approved' },
    opinion: 'Es un paso adelante pero faltan muchas cosas',
    selectedAgent: 'analytical',
    agentResponse: 'Cada paso cuenta en el cambio social',
    agentQuestion: '¿Qué sigue siendo importante?',
    followUpResponse: 'Salarios dignos y educación',
    finalMood: 58,
    moodShift: 13,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 36000000,
    updatedAt: Date.now() - 36000000,
    status: 'completed',
    currentStep: 4
  },
  {
    id: '6',
    initialMood: 50,
    city: 'Quito',
    news: { title: 'Education Reform', description: 'New school curriculum implemented' },
    opinion: 'Los cambios en educación son necesarios pero requieren paciencia',
    selectedAgent: 'reflective',
    agentResponse: 'La educación es inversión en futuro',
    agentQuestion: '¿En qué deberían enfocarse?',
    followUpResponse: 'En pensamiento crítico y creatividad',
    finalMood: 62,
    moodShift: 12,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 24000000,
    updatedAt: Date.now() - 24000000,
    status: 'completed',
    currentStep: 4
  },
  {
    id: '7',
    initialMood: 38,
    city: 'Caracas',
    news: { title: 'Social Initiative', description: 'Community support program launches' },
    opinion: 'Hay pequeñas luces en medio de los tiempos difíciles',
    selectedAgent: 'compassionate',
    agentResponse: 'La comunidad es nuestra fortaleza',
    agentQuestion: '¿Cómo podemos apoyarnos?',
    followUpResponse: 'Juntos, con solidaridad',
    finalMood: 48,
    moodShift: 10,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 12000000,
    updatedAt: Date.now() - 12000000,
    status: 'completed',
    currentStep: 4
  },
  {
    id: '8',
    initialMood: 55,
    city: 'Buenos Aires',
    news: { title: 'Tech Growth', description: 'Tech sector shows growth' },
    opinion: 'La tecnología está creando nuevas oportunidades',
    selectedAgent: 'analytical',
    agentResponse: 'La innovación es clave para el desarrollo',
    agentQuestion: '¿Qué impacto ves?',
    followUpResponse: 'Emprendimientos jóvenes emergiendo',
    finalMood: 72,
    moodShift: 17,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 6000000,
    updatedAt: Date.now() - 6000000,
    status: 'completed',
    currentStep: 4
  },
  {
    id: '9',
    initialMood: 48,
    city: 'Mexico City',
    news: { title: 'Environmental Project', description: 'Park restoration initiative' },
    opinion: 'El cuidado del ambiente es urgente pero veo iniciativas positivas',
    selectedAgent: 'reflective',
    agentResponse: 'La naturaleza es nuestra responsabilidad',
    agentQuestion: '¿Cómo participas tú?',
    followUpResponse: 'Voluntariado en proyectos verdes',
    finalMood: 66,
    moodShift: 18,
    emotionalTransform: 'improved',
    createdAt: Date.now() - 3000000,
    updatedAt: Date.now() - 3000000,
    status: 'completed',
    currentStep: 4
  }
]
